name: 🚀 Construir, Enviar Imagens Docker e Deploy no Kubernetes (Universal)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: app-demo
      BACKEND_TAG: ${{ github.sha }}
      FRONTEND_TAG: ${{ github.sha }}
      INFRA_BASE: https://raw.githubusercontent.com/dissectedv/loja-infra/main
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

    steps:
      - name: 1️⃣ Baixar código
        uses: actions/checkout@v3

      - name: 2️⃣ Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3️⃣ Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4️⃣ Buildar e enviar imagem do Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USER }}/backend:${{ github.sha }}
          no-cache: true
          pull: true

      - name: 5️⃣ Buildar e enviar imagem do Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USER }}/frontend:${{ github.sha }}
          no-cache: true
          pull: true

      - name: 6️⃣ Instalar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: 7️⃣ Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE
          echo "✅ kubeconfig aplicado com sucesso"

      - name: 8️⃣ Baixar manifestos Kubernetes (infra externa)
        run: |
          set -e
          mkdir -p k8s
          for f in 00-namespace.yaml 01-secret-mysql.yaml 02-configmap-app.yaml 03-configmap-mysql-init.yaml 04-configmap-mysql-dump.yaml 10-mysql-service.yaml 11-mysql-statefulset.yaml 20-backend-service.yaml 21-backend-deployment.yaml 30-frontend-service.yaml 31-frontend-deployment.yaml 50-job-mysql-import.yaml kustomization.yaml; do
            echo "⬇  Baixando $f"
            curl -fsSL "$INFRA_BASE/$f" -o "k8s/$f"
          done
          test -s k8s/kustomization.yaml || { echo "❌ Falha ao baixar kustomization.yaml"; exit 1; }
          echo "✅ Manifestos baixados com sucesso"

      - name: 9️⃣ Aplicar manifestos no cluster
        run: |
          kubectl apply -k k8s --validate=false --insecure-skip-tls-verify
          echo "✅ Manifestos aplicados com sucesso"

      - name: 🔟 Atualizar imagens nos deployments
        run: |
          kubectl set image deployment/backend app=${{ secrets.DOCKER_USER }}/backend:${{ github.sha }} -n $NAMESPACE --insecure-skip-tls-verify
          kubectl set image deployment/frontend web=${{ secrets.DOCKER_USER }}/frontend:${{ github.sha }} -n $NAMESPACE --insecure-skip-tls-verify
          echo "✅ Imagens atualizadas"

      - name: 1️⃣1️⃣ Aguardar rollout dos deployments
        run: |
          kubectl rollout status deployment/backend -n $NAMESPACE --timeout=180s || kubectl logs -l app.kubernetes.io/name=backend -n $NAMESPACE --tail=50
          kubectl rollout status deployment/frontend -n $NAMESPACE --timeout=180s || kubectl logs -l app.kubernetes.io/name=frontend -n $NAMESPACE --tail=50
          echo "✅ Rollouts concluídos"

      - name: 1️⃣2️⃣ Executar job SQL de importação (se necessário)
        run: |
          kubectl delete job mysql-import-job -n $NAMESPACE --ignore-not-found
          kubectl apply -f k8s/50-job-mysql-import.yaml -n $NAMESPACE
          echo "✅ Job SQL aplicada (se o BD estiver vazio, será importado)"

      - name: 1️⃣3️⃣ Resumo final do deploy
        run: |
          echo "✅ Backend e Frontend atualizados com sucesso"
          echo "📦 Tags Docker usadas: ${{ github.sha }}"
          echo "🚀 Deploy concluído!"